In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import prophet
from sklearn.metrics import mean_squared_error, mean_absolute_error

In [3]:
df=pd.read_csv('/Users/rui/Desktop/apple_stock_data.csv')

In [4]:
df

            Date  Close Price  High Price   Low Price  Open Price     Volume
0     04-01-2010     6.431897    6.446623    6.382908    6.414465  493729600
1     05-01-2010     6.443017    6.479382    6.409055    6.449629  601904800
2     06-01-2010     6.340532    6.468563    6.333920    6.443017  552160000
3     07-01-2010     6.328810    6.371488    6.282827    6.363974  477131200
4     08-01-2010     6.370885    6.371487    6.283128    6.320394  447610800
...          ...          ...         ...         ...         ...        ...
3768  23-12-2024   254.655716  255.034791  252.840088  254.156919   40858800
3769  24-12-2024   257.578674  257.588630  254.675658  254.875189   23234700
3770  26-12-2024   258.396667  259.474086  257.010028  257.568678   27237100
3771  27-12-2024   254.974930  258.077462  252.451019  257.209530   42355300
3772  30-12-2024   251.593094  252.889969  250.146586  251.623020   35557500

[3773 rows x 6 columns]

In [6]:
from pandas.api.types import CategoricalDtype

In [12]:
df['Date'] = pd.to_datetime(df['Date'], format='%d-%m-%Y'
)

In [24]:
df['ds']=df['Date'].dt.strftime('%Y-%m-%d')

In [44]:
from numpy import log
df['volume']=np.log1p(df['Volume'])
feature=['Date','volume']
df[feature]

           Date     volume
0    2010-01-04  20.017499
1    2010-01-05  20.215610
2    2010-01-06  20.129348
3    2010-01-07  19.983302
4    2010-01-08  19.919435
...         ...        ...
3768 2024-12-23  17.525633
3769 2024-12-24  16.961157
3770 2024-12-26  17.120091
3771 2024-12-27  17.561604
3772 2024-12-30  17.386662

[3773 rows x 2 columns]

In [26]:
df['datetime']=df.index

In [27]:
df['datetime']

0          0
1          1
2          2
3          3
4          4
        ...
3768    3768
3769    3769
3770    3770
3771    3771
3772    3772
Name: datetime, Length: 3773, dtype: int64

In [28]:
df

,Date,Close Price,High Price,Low Price,Open Price,Volume,ds,datetime
0,2010-01-04,6.431897,6.446623,6.382908,6.414465,493729600,2010-01-04,0
1,2010-01-05,6.443017,6.479382,6.409055,6.449629,601904800,2010-01-05,1
2,2010-01-06,6.340532,6.468563,6.333920,6.443017,552160000,2010-01-06,2
3,2010-01-07,6.328810,6.371488,6.282827,6.363974,477131200,2010-01-07,3
4,2010-01-08,6.370885,6.371487,6.283128,6.320394,447610800,2010-01-08,4
...,...,...,...,...,...,...,...,...
3768,2024-12-23,254.655716,255.034791,252.840088,254.156919,40858800,2024-12-23,3768
3769,2024-12-24,257.578674,257.588630,254.675658,254.875189,23234700,2024-12-24,3769
3770,2024-12-26,258.396667,259.474086,257.010028,257.568678,27237100,2024-12-26,3770
3771,2024-12-27,254.974930,258.077462,252.451019,257.209530,42355300,2024-12-27,3771
3772,2024-12-30,251.593094,252.889969,250.146586,251.623020,35557500,2024-12-30,3772

In [48]:
split_time='2017-06-30'
df_train=df[feature].loc[df['ds']<=split_time].copy()

In [49]:
df_train

           Date     volume
0    2010-01-04  20.017499
1    2010-01-05  20.215610
2    2010-01-06  20.129348
3    2010-01-07  19.983302
4    2010-01-08  19.919435
...         ...        ...
1882 2017-06-26  18.448000
1883 2017-06-27  18.411111
1884 2017-06-28  18.296586
1885 2017-06-29  18.651773
1886 2017-06-30  18.338346

[1887 rows x 2 columns]

In [45]:
df_test = df[feature].loc[df['ds'] > split_time].copy()

In [46]:
df_test

           Date     volume
1887 2017-07-03  17.860511
1888 2017-07-05  18.273090
1889 2017-07-06  18.385211
1890 2017-07-07  18.156804
1891 2017-07-10  18.250632
...         ...        ...
3768 2024-12-23  17.525633
3769 2024-12-24  16.961157
3770 2024-12-26  17.120091
3771 2024-12-27  17.561604
3772 2024-12-30  17.386662

[1886 rows x 2 columns]

In [53]:
df_train_prophet=df_train.reset_index().rename(columns={'Date':'ds','volume':'y'})

In [54]:
df_train_prophet

      index         ds          y
0         0 2010-01-04  20.017499
1         1 2010-01-05  20.215610
2         2 2010-01-06  20.129348
3         3 2010-01-07  19.983302
4         4 2010-01-08  19.919435
...     ...        ...        ...
1882   1882 2017-06-26  18.448000
1883   1883 2017-06-27  18.411111
1884   1884 2017-06-28  18.296586
1885   1885 2017-06-29  18.651773
1886   1886 2017-06-30  18.338346

[1887 rows x 3 columns]

In [61]:
import prophet
from prophet import Prophet

In [62]:
model = Prophet()

model.fit(df_train_prophet)

In [63]:
model.fit(df_train_prophet)

16:14:57 - cmdstanpy - INFO - Chain [1] start processing
16:14:57 - cmdstanpy - INFO - Chain [1] done processing

In [67]:
df_test_prophet=df_test.reset_index().rename(columns={'Date':'ds','volume':'y'})
df_test_prophet

      index         ds          y
0      1887 2017-07-03  17.860511
1      1888 2017-07-05  18.273090
2      1889 2017-07-06  18.385211
3      1890 2017-07-07  18.156804
4      1891 2017-07-10  18.250632
...     ...        ...        ...
1881   3768 2024-12-23  17.525633
1882   3769 2024-12-24  16.961157
1883   3770 2024-12-26  17.120091
1884   3771 2024-12-27  17.561604
1885   3772 2024-12-30  17.386662

[1886 rows x 3 columns]

In [69]:
df_test_predict=model.predict(df_test_prophet)
df_test_predict

,ds,trend,yhat_lower,yhat_upper,trend_lower,trend_upper,additive_terms,additive_terms_lower,additive_terms_upper,weekly,weekly_lower,weekly_upper,yearly,yearly_lower,yearly_upper,multiplicative_terms,multiplicative_terms_lower,multiplicative_terms_upper,yhat
0,2017-07-03,18.317982,17.750501,18.651068,18.317982,18.317982,-0.110229,-0.110229,-0.110229,0.021934,0.021934,0.021934,-0.132164,-0.132164,-0.132164,0.0,0.0,0.0,18.207752
1,2017-07-05,18.315809,17.838251,18.704632,18.315809,18.315809,-0.064190,-0.064190,-0.064190,0.058026,0.058026,0.058026,-0.122216,-0.122216,-0.122216,0.0,0.0,0.0,18.251619
2,2017-07-06,18.314722,17.779763,18.653430,18.314722,18.314722,-0.113354,-0.113354,-0.113354,0.002564,0.002564,0.002564,-0.115918,-0.115918,-0.115918,0.0,0.0,0.0,18.201368
3,2017-07-07,18.313636,17.793965,18.663322,18.313636,18.313636,-0.067047,-0.067047,-0.067047,0.041864,0.041864,0.041864,-0.108910,-0.108910,-0.108910,0.0,0.0,0.0,18.246589
4,2017-07-10,18.310377,17.813730,18.700048,18.310377,18.310377,-0.063150,-0.063150,-0.063150,0.021934,0.021934,0.021934,-0.085084,-0.085084,-0.085084,0.0,0.0,0.0,18.247227
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1881,2024-12-23,15.351996,9.898250,20.533453,10.201880,20.779774,-0.241689,-0.241689,-0.241689,0.021934,0.021934,0.021934,-0.263623,-0.263623,-0.263623,0.0,0.0,0.0,15.110307
1882,2024-12-24,15.350910,9.907544,20.541490,10.193188,20.780115,-0.211788,-0.211788,-0.211788,0.066886,0.066886,0.066886,-0.278674,-0.278674,-0.278674,0.0,0.0,0.0,15.139122
1883,2024-12-26,15.348737,9.820070,20.465824,10.183410,20.779370,-0.297403,-0.297403,-0.297403,0.002564,0.002564,0.002564,-0.299966,-0.299966,-0.299966,0.0,0.0,0.0,15.051334
1884,2024-12-27,15.347650,9.882471,20.661479,10.179612,20.779711,-0.263790,-0.263790,-0.263790,0.041864,0.041864,0.041864,-0.305653,-0.305653,-0.305653,0.0,0.0,0.0,15.083860
1885,2024-12-30,15.344391,9.668819,20.454359,10.175844,20.777880,-0.278884,-0.278884,-0.278884,0.021934,0.021934,0.021934,-0.300818,-0.300818,-0.300818,0.0,0.0,0.0,15.065507

In [70]:
np.sqrt(mean_squared_error(y_true=df_test_prophet['y'],y_pred=df_test_predict['yhat']))

np.float64(1.5899918530012727)

In [91]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.models import Sequential
from sklearn.preprocessing import StandardScaler
from tensorflow.keras.layers import LSTM, Dense,Dropout
import keras_tuner as kt
df

,Date,Close Price,High Price,Low Price,Open Price,Volume,ds,datetime,volume
0,2010-01-04,6.431897,6.446623,6.382908,6.414465,493729600,2010-01-04,0,20.017499
1,2010-01-05,6.443017,6.479382,6.409055,6.449629,601904800,2010-01-05,1,20.215610
2,2010-01-06,6.340532,6.468563,6.333920,6.443017,552160000,2010-01-06,2,20.129348
3,2010-01-07,6.328810,6.371488,6.282827,6.363974,477131200,2010-01-07,3,19.983302
4,2010-01-08,6.370885,6.371487,6.283128,6.320394,447610800,2010-01-08,4,19.919435
...,...,...,...,...,...,...,...,...,...
3768,2024-12-23,254.655716,255.034791,252.840088,254.156919,40858800,2024-12-23,3768,17.525633
3769,2024-12-24,257.578674,257.588630,254.675658,254.875189,23234700,2024-12-24,3769,16.961157
3770,2024-12-26,258.396667,259.474086,257.010028,257.568678,27237100,2024-12-26,3770,17.120091
3771,2024-12-27,254.974930,258.077462,252.451019,257.209530,42355300,2024-12-27,3771,17.561604
3772,2024-12-30,251.593094,252.889969,250.146586,251.623020,35557500,2024-12-30,3772,17.386662

In [107]:
feature=['Close Price','High Price','Low Price','Open Price','volume']
df_model=df[feature].dropna()
scaler=StandardScaler()
df_model_scaled=scaler.fit_transform(df_model)
lookback=5
def create_sequence(data,lookback):
    x,y=[],[]
    for i in range(lookback,len(data)):
        x.append(data[i-lookback:i])
        y.append(data[i,-1])
    return np.array(x),np.array(y)
x,y=create_sequence(df_model_scaled,lookback)
num_trained=int(0.8*(len(x)))
x_train,x_test=x[:num_trained],x[num_trained:]
y_train,y_test=y[:num_trained],y[num_trained:]
def build_model(hp):
    model=Sequential()
    model.add(LSTM(hp.Int('units',min_value=50,max_value=210,step=16)
                   ,return_sequences=False,
                   input_shape=(x.shape[1],x.shape[2])))
    model.add(Dropout(hp.Float('Dropout',0.1,0.5,step=0.1)))
    model.add(Dense(1))
    model.compile(optimizer='Adam',loss='mse')
    return model
tuner=kt.RandomSearch(build_model,
                      objective='loss',
                      max_trials=5,
                      executions_per_trial=1)
tuner.search(x_train, y_train, epochs=20, batch_size=32)
best_hp=tuner.get_best_hyperparameters(1)[0]
best_model=tuner.get_best_models(num_models=1)[0]

Reloading Tuner from ./untitled_project/tuner0.json

/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/keras/src/layers/rnn/rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)
/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/keras/src/saving/saving_lib.py:802: UserWarning: Skipping variable loading for optimizer 'adam', because it has 2 variables whereas the saved optimizer has 12 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

In [137]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split, TimeSeriesSplit, GridSearchCV,KFold
from skopt import BayesSearchCV
from xgboost import XGBRegressor
from skopt.space import Real, Integer

In [138]:
x_train

      Close Price  Open Price  High Price   Low Price
2659    90.647888   91.731743   91.909149   90.643023
1474    26.383442   26.412816   26.677169   26.223022
1918    37.637241   37.868749   38.002038   37.450165
3684   226.045425  224.869566  227.420596  223.544223
1164    22.237160   21.989418   22.270340   21.969509
...           ...         ...         ...         ...
1130    20.584175   20.584175   20.705233   20.498334
1294    28.724703   29.342511   29.351435   28.581960
860     13.664727   13.681305   13.836953   13.621748
3507   194.287201  192.788169  194.565164  192.262023
3174   169.617828  167.370714  169.686811  166.956758

[2641 rows x 4 columns]

In [139]:
features=['Close Price','Open Price','High Price','Low Price']

In [140]:
df_new=df[features]

In [141]:
df_new
x=df_new
y=df['volume']

In [142]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=42)

In [158]:
pipe=Pipeline([('scaler',StandardScaler()),
              ('estimator',XGBRegressor)])

In [159]:
cv_strategy=TimeSeriesSplit(n_splits=10)
para_space={'estimator__n_estimators':Integer(100,200),
            'estimator__max_depth':Integer(3,7),
            'estimator__learning_rate':Real(0.01,0.1)}

In [163]:

pipe=Pipeline([('scaler',StandardScaler()),
              ('estimator',XGBRegressor())])
cv_strategy=TimeSeriesSplit(n_splits=10)
para_space={'estimator__n_estimators':Integer(100,200),
            'estimator__max_depth':Integer(3,7),
            'estimator__learning_rate':Real(0.01,0.1,prior='log-uniform')}
bayes=BayesSearchCV(estimator=pipe,
                    search_spaces=para_space,
                    n_iter=10,
                    cv=cv_strategy,
                    scoring='neg_mean_squared_error')
bayes.fit(x_train,y_train)

BayesSearchCV(cv=TimeSeriesSplit(gap=0, max_train_size=None, n_splits=10, test_size=None),
              estimator=Pipeline(steps=[('scaler', StandardScaler()),
                                        ('estimator',
                                         XGBRegressor(base_score=None,
                                                      booster=None,
                                                      callbacks=None,
                                                      colsample_bylevel=None,
                                                      colsample_bynode=None,
                                                      colsample_bytree=None,
                                                      device=None,
                                                      early_stopping_rounds=None,
                                                      enable_categorical=False,
                                                      eval_met...
                                                      random_state=None, ...))]),
              n_iter=10, scoring='neg_mean_squared_error',
              search_spaces={'estimator__learning_rate': Real(low=0.01, high=0.1, prior='log-uniform', transform='normalize'),
                             'estimator__max_depth': Integer(low=3, high=7, prior='uniform', transform='normalize'),
                             'estimator__n_estimators': Integer(low=100, high=200, prior='uniform', transform='normalize')})

In [173]:
bayes.best_score_

np.float64(-0.1454104482044445)


pipe=Pipeline([('scaler',StandardScaler()),
              ('estimator',XGBRegressor())])
cv_strategy=TimeSeriesSplit(n_splits=10)
para_space={'estimator__n_estimators':[100,200],
            'estimator__max_depth':[3,7],
            'estimator__learning_rate':[0.1,0.2,0.3]}
grid=GridSearchCV(estimator=pipe,
                   param_grid=para_space,
                   cv=cv_strategy,
                   scoring='neg_mean_squared_error')
grid.fit(x_train,y_train)
grid.best_score_

In [171]:

pipe=Pipeline([('scaler',StandardScaler()),
              ('estimator',XGBRegressor())])
cv_strategy=TimeSeriesSplit(n_splits=10)
para_space={'estimator__n_estimators':[100,200],
            'estimator__max_depth':[3,7],
            'estimator__learning_rate':[0.1,0.2,0.3]}
grid=GridSearchCV(estimator=pipe,
                   param_grid=para_space,
                   cv=cv_strategy,
                   scoring='neg_mean_squared_error')
grid.fit(x_train,y_train)
grid.best_score_

np.float64(-0.145078687959397)

In [172]:

pipe=Pipeline([('scaler',StandardScaler()),
              ('estimator',XGBRegressor())])
cv_strategy=TimeSeriesSplit(n_splits=10)
para_space={'estimator__n_estimators':[100,200],
            'estimator__max_depth':[3,7],
            'estimator__learning_rate':[0.1,0.2,0.3]}
grid=GridSearchCV(estimator=pipe,
                   param_grid=para_space,
                   cv=cv_strategy,
                   scoring='neg_mean_squared_error')
grid.fit(x_train,y_train)
grid.best_score_

np.float64(-0.145078687959397)